### ISSUE TITLE
Exporting backup when there is no data

### ISSUE THREAD

**Issue by ed255** [iden3/Wallet#29]
Current: The app allows exporting a backup of the data even when there is no identity created.

Expected: I think the exporting button should be disabled when there's no data to export.

**Comment by ed255** [comment]
discuss with @rafal-na

**Comment by cjgarde** [comment]
The point is to have always the same view to don't confuse user. 
Maybe, we can disable the "export" button when user is creating first identity.

What do you think? Any other ideas?

**Comment by ed255** [comment]
I think disabling the export button when the user is creating the first identity is a good idea.  The button could be shown in gray color and it would do nothing.

**Comment by cjgarde** [comment]
Ok! Fixed with this approach! :)
