### ISSUE TITLE
"Import my wallet backup" doesn't look clickable

### ISSUE THREAD

**Issue by ed255** [iden3/Wallet#34]
Current: The "Import my wallet backup" button doesn't have a button layout.  It has the same appearance as non-button text.

Expected: Give the user some clue that they can click on "Import my wallet backup" and it's not just regular text.

discuss with @rafal-na

**Comment by cjgarde** [comment]
We can change the colour when hovering. 
I change the label as "enhancement" to do it.

**Comment by cjgarde** [comment]
Fixed!
