### ISSUE TITLE
Wrong section highlighted

### ISSUE THREAD

**Issue by ed255** [iden3/Wallet#41]
OS: Linux (Arch Linux)
Browser: Firefox 65.0

Current: When loading the website with a '#/dashboard' or any other section in the URL, the name of the section in the tabs UI stays in blue during the whole time, even after changing the section.

![](https://i.imgur.com/2n8Lubf.png)

Expected: The highlighted section should change according to the current section.

@cjgarde says: MP: To be fixed after HP issues

**Comment by cjgarde** [comment]
Right! I assign to myself to fix it!
Thanks!
Regards.

**Comment by cjgarde** [comment]
Fixed!
